version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile_Dev

    volumes:
      - "./build/libs/consignment-0.0.1-SNAPSHOT.jar:/app/app.jar"
    container_name: app
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=admin

  postgresql:
    image: postgres:13.0-alpine
    container_name: postgresql
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin



volumes:
  postgresql-data: