server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.freightmate.consignment: info
